# Generated by Django 5.1.4 on 2025-01-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subjects',
            field=models.ManyToManyField(to='subjects.subject'),
        ),
    ]
